package org.atlasapi.generation.model;

import java.util.Set;

/**
 * Represents the information relevant to a particular model class,
 * for outputting via the Meta API. Implementations of this interface
 * will be generated by an annotation processor running over the Atlas model
 * classes  
 * 
 * @author Oliver Hall (oli@metabroadcast.com)
 *
 */
public interface ModelClassInfo {

	String key();
	String description();
	Set<FieldInfo> fields();
	Class<?> describedType();
}
