package org.atlasapi.content;


public enum ContentColumn {
    TYPE,
    SOURCE,
    IDENTIFICATION,
    DESCRIPTION,
    BROADCASTS,
    LOCATIONS,
    CHILDREN,
    CHILD_UPDATED,
    SECONDARY,
    PEOPLE,
    CLIPS,
    KEYPHRASES,
    LINKS,
    TOPICS,
    GROUPS,
    SEGMENTS,
    UPCOMING_CONTENT,
    AVAILABLE_CONTENT,
    ITEM_SUMMARIES,
    ACTIVELY_PUBLISHED,
    GENERIC_DESCRIPTION,
    CONTAINER_SUMMARY,
    CONTAINER_REF,
    SERIES_REF,
    }
